name: pdf_samples
description: Flutter project to test differents PDF Viewers pub libs

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependency_overrides:
  path: 1.7.0
  convert: ^3.0.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  advance_pdf_viewer: ^1.2.2
  pdf_viewer_plugin: 2.0.1
  permission_handler: ^5.1.0+2
  path_provider: ^1.6.27
  path: 1.7.0
  external_path: 1.0.1
  flutter_share: 2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

